# create a new VM from a template

- name: new VM from template
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    vcenter_hostname: hostname
    vcenter_user: administrator@
    vcenter_pass: password
    esxhost: esx_host_ip
    datastore: datastore1
    vmtemplate: VM1
    name: "new_vm"
    notes: Ansible_Test
    dumpfacts: False
  tasks:
    - name: Create VM from template
      vmware_guest:
        validate_certs: False
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        esxi_hostname: "{{ esxhost }}"
        datacenter: dc
        name: "{{ name }}"
        template: "{{ vmtemplate }}"
        disk:
          - size_gb: "{{ disk_size | default(30) }}"
            type: thin
            datastore: "{{ datastore }}"
        networks:
        - name: VM Network
          type: dhcp
        hardware:
          memory_mb: "{{ vm_memory | default(1024) }}"
        wait_for_ip_address: True
        state: present
      register: newvm

    - name: IP address info
      debug:
        msg: "{{ newvm.instance.ipv4 }} {{ name }}"
